export const ON_USERS_LOAD_START = 'ON_USERS_LOAD_START';
export const ON_USERS_LOAD_SUCCESS = 'ON_USERS_LOAD_SUCCESS';
export const ON_USERS_LOAD_ERROR = 'ON_USERS_LOAD_ERROR';

export const ON_USER_ADD_START = 'ON_USER_ADD_START';
export const ON_USER_ADD_SUCCESS = 'ON_USER_ADD_SUCCESS';
export const ON_USER_ADD_ERROR = 'ON_USER_ADD_ERROR';

export const ON_USER_REMOVE_START = 'ON_USER_REMOVE_START';
export const ON_USER_REMOVE_SUCCESS = 'ON_USER_REMOVE_SUCCESS';
export const ON_USER_REMOVE_ERROR = 'ON_USER_REMOVE_ERROR';
